// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobile404API.Data;

#nullable disable

namespace Mobile404API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mobile404API.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5251),
                            ImageFileName = "samsung.jpg",
                            IsActive = true,
                            Name = "سامسونگ",
                            Slug = "samsung"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5269),
                            ImageFileName = "nokia.jpg",
                            IsActive = true,
                            Name = "نوکیا",
                            Slug = "nokia"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5273),
                            ImageFileName = "xiaomi.jpg",
                            IsActive = true,
                            Name = "شیائومی",
                            Slug = "xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5276),
                            ImageFileName = "apple.jpg",
                            IsActive = true,
                            Name = "اپل",
                            Slug = "apple"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5279),
                            ImageFileName = "huawei.jpg",
                            IsActive = true,
                            Name = "هوآوی",
                            Slug = "huawei"
                        });
                });

            modelBuilder.Entity("Mobile404API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Mobile404API.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Galleries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6388),
                            ImageFileName = "samsung-a14-1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6392),
                            ImageFileName = "samsung-a14-2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6395),
                            ImageFileName = "huawei-nova-y71-1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6397),
                            ImageFileName = "huawei-nova-y71-2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6400),
                            ImageFileName = "huawei-nova-y71-3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6402),
                            ImageFileName = "xiaomi-redmi-note-13-1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6404),
                            ImageFileName = "Galaxy-A05-1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6406),
                            ImageFileName = "Galaxy-A05-2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6409),
                            ImageFileName = "Galaxy-M13-1.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6411),
                            ImageFileName = "Galaxy-M13-2.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6413),
                            ImageFileName = "Galaxy-M13-3.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6418),
                            ImageFileName = "Galaxy-A15-1.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6420),
                            ImageFileName = "Galaxy-A15-2.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6422),
                            ImageFileName = "Galaxy-A15-3.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6424),
                            ImageFileName = "Galaxy-A05s-1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6427),
                            ImageFileName = "Galaxy-A05s-2.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6429),
                            ImageFileName = "Galaxy-A05s-3.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6431),
                            ImageFileName = "Galaxy-A23-1.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6433),
                            ImageFileName = "Galaxy-A23-2.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6435),
                            ImageFileName = "Galaxy-A23-3.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6438),
                            ImageFileName = "Galaxy-A25-1.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6440),
                            ImageFileName = "Galaxy-A25-2.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6442),
                            ImageFileName = "Galaxy-A25-3.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6444),
                            ImageFileName = "Galaxy-A34-1.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6446),
                            ImageFileName = "Galaxy-A34-2.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6448),
                            ImageFileName = "Galaxy-A35-1.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6450),
                            ImageFileName = "Galaxy-A35-2.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6453),
                            ImageFileName = "Galaxy-A54-1.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6455),
                            ImageFileName = "Galaxy-A54-2.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6456),
                            ImageFileName = "Galaxy-A55-1.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6458),
                            ImageFileName = "Galaxy-A55-2.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6462),
                            ImageFileName = "Galaxy-A55-3.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6465),
                            ImageFileName = "Galaxy-S21-1.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6467),
                            ImageFileName = "Galaxy-S23-1.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6470),
                            ImageFileName = "Galaxy-S23-2.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6475),
                            ImageFileName = "Galaxy-S23-Ultra-1.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6477),
                            ImageFileName = "Galaxy-S24-Ultra-1.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6479),
                            ImageFileName = "Galaxy-S24-Ultra-2.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6481),
                            ImageFileName = "Galaxy-S24-Ultra-3.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6484),
                            ImageFileName = "Redmi-Note-12S-1.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6486),
                            ImageFileName = "Redmi-Note-12S-2.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6489),
                            ImageFileName = "Redmi-Note-13-1.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6491),
                            ImageFileName = "Redmi-Note-13-2.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6494),
                            ImageFileName = "Redmi-Note-13-3.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6496),
                            ImageFileName = "Redmi-Note-12-1.jpg",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6498),
                            ImageFileName = "Redmi-Note-12-Turbo-1.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6500),
                            ImageFileName = "Redmi-Note-12-Turbo-2.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6502),
                            ImageFileName = "Redmi-Note-12-Turbo-3.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6504),
                            ImageFileName = "Poco-F5-1.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6506),
                            ImageFileName = "Poco-F5-2.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6509),
                            ImageFileName = "Poco-F5-3.jpg",
                            ProductId = 23
                        });
                });

            modelBuilder.Entity("Mobile404API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Mobile404API.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("Mobile404API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Camera")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hard")
                        .HasColumnType("int");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6201),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A14"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6207),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi 12"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 5,
                            Camera = 48,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6213),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل هوآوی مدل nova Y71"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6217),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 13 4G"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6222),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A05"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6227),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy M13"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6232),
                            Description = "",
                            Hard = 128,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A15"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6240),
                            Description = "",
                            Hard = 128,
                            Ram = 6,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A05s"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6245),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A23 "
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6250),
                            Description = "",
                            Hard = 128,
                            Ram = 6,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A25"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            Camera = 48,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6256),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A34 5G "
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6261),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A35"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6267),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A54 5G"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6272),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A55"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 1,
                            Camera = 12,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6277),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S21 FE 5G"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6283),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S23 FE"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 1,
                            Camera = 200,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6288),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S23 Ultra"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            Camera = 200,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6294),
                            Description = "",
                            Hard = 512,
                            Ram = 12,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6299),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 12S"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6304),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 13 5G"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6310),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 12 Pro 5G"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 3,
                            Camera = 64,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6315),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 12 Turbo 5G"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 3,
                            Camera = 64,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6320),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل شیائومی مدل Poco F5 5G"
                        });
                });

            modelBuilder.Entity("Mobile404API.Models.ProductToShop", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ShopId");

                    b.HasIndex("ShopId");

                    b.ToTable("ProductToShops");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ShopId = 1,
                            Price = 6000000
                        },
                        new
                        {
                            ProductId = 2,
                            ShopId = 1,
                            Price = 6900000
                        },
                        new
                        {
                            ProductId = 3,
                            ShopId = 1,
                            Price = 6200000
                        },
                        new
                        {
                            ProductId = 4,
                            ShopId = 1,
                            Price = 8840000
                        },
                        new
                        {
                            ProductId = 5,
                            ShopId = 1,
                            Price = 8740000
                        },
                        new
                        {
                            ProductId = 6,
                            ShopId = 1,
                            Price = 5699000
                        },
                        new
                        {
                            ProductId = 7,
                            ShopId = 1,
                            Price = 6079000
                        },
                        new
                        {
                            ProductId = 8,
                            ShopId = 1,
                            Price = 6470000
                        },
                        new
                        {
                            ProductId = 9,
                            ShopId = 1,
                            Price = 7399000
                        },
                        new
                        {
                            ProductId = 10,
                            ShopId = 1,
                            Price = 9549000
                        },
                        new
                        {
                            ProductId = 11,
                            ShopId = 1,
                            Price = 12999000
                        },
                        new
                        {
                            ProductId = 12,
                            ShopId = 1,
                            Price = 15287000
                        },
                        new
                        {
                            ProductId = 13,
                            ShopId = 1,
                            Price = 16990000
                        },
                        new
                        {
                            ProductId = 14,
                            ShopId = 1,
                            Price = 20980000
                        },
                        new
                        {
                            ProductId = 15,
                            ShopId = 1,
                            Price = 21150000
                        },
                        new
                        {
                            ProductId = 16,
                            ShopId = 1,
                            Price = 25850000
                        },
                        new
                        {
                            ProductId = 17,
                            ShopId = 1,
                            Price = 57950000
                        },
                        new
                        {
                            ProductId = 19,
                            ShopId = 1,
                            Price = 8530000
                        },
                        new
                        {
                            ProductId = 20,
                            ShopId = 1,
                            Price = 11540000
                        },
                        new
                        {
                            ProductId = 21,
                            ShopId = 1,
                            Price = 12600000
                        },
                        new
                        {
                            ProductId = 22,
                            ShopId = 1,
                            Price = 18799000
                        },
                        new
                        {
                            ProductId = 23,
                            ShopId = 1,
                            Price = 17999000
                        },
                        new
                        {
                            ProductId = 2,
                            ShopId = 2,
                            Price = 6950000
                        },
                        new
                        {
                            ProductId = 20,
                            ShopId = 2,
                            Price = 11440000
                        },
                        new
                        {
                            ProductId = 10,
                            ShopId = 2,
                            Price = 9549000
                        });
                });

            modelBuilder.Entity("Mobile404API.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5622),
                            Name = "موبایل404",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5628),
                            Name = "علی شاپ",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Mobile404API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(5979),
                            Email = "admin@gmail.com",
                            IsActive = false,
                            Name = "ادمین",
                            Password = "81-DC-9B-DB-52-D0-4D-C2-00-36-DB-D8-31-3E-D0-55",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6025),
                            Email = "ali@gmail.com",
                            IsActive = false,
                            Name = "علی",
                            Password = "81-DC-9B-DB-52-D0-4D-C2-00-36-DB-D8-31-3E-D0-55",
                            Role = "seller"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 9, 19, 2, 55, 209, DateTimeKind.Local).AddTicks(6059),
                            Email = "tara@gmail.com",
                            IsActive = false,
                            Name = "تارا",
                            Password = "81-DC-9B-DB-52-D0-4D-C2-00-36-DB-D8-31-3E-D0-55",
                            Role = "client"
                        });
                });

            modelBuilder.Entity("Mobile404API.Models.Comment", b =>
                {
                    b.HasOne("Mobile404API.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mobile404API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mobile404API.Models.Gallery", b =>
                {
                    b.HasOne("Mobile404API.Models.Product", "Product")
                        .WithMany("Galleries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mobile404API.Models.Order", b =>
                {
                    b.HasOne("Mobile404API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mobile404API.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.HasOne("Mobile404API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mobile404API.Models.Product", b =>
                {
                    b.HasOne("Mobile404API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Mobile404API.Models.ProductToShop", b =>
                {
                    b.HasOne("Mobile404API.Models.Product", "Product")
                        .WithMany("ProductToShops")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mobile404API.Models.Shop", "Shop")
                        .WithMany("ProductToShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Mobile404API.Models.Shop", b =>
                {
                    b.HasOne("Mobile404API.Models.User", "User")
                        .WithMany("Shop")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mobile404API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Mobile404API.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Galleries");

                    b.Navigation("ProductToShops");
                });

            modelBuilder.Entity("Mobile404API.Models.Shop", b =>
                {
                    b.Navigation("ProductToShops");
                });

            modelBuilder.Entity("Mobile404API.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
